name: Test
on:
  push:
    branches: ['**']
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    env:
      REACT_APP_firebase_apiKey: 'AIzaSyAfNFU1GhESw6oZ1sY2kUPJwRwXDEyDnF0'
      REACT_APP_firebase_authDomain: 'maze-a2b08.firebaseapp.com'
      REACT_APP_firebase_databaseURL: 'https://maze-a2b08-default-rtdb.asia-southeast1.firebasedatabase.app/'
      REACT_APP_firebase_storageBucket: 'maze-a2b08.appspot.com'
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
